create_vscode_settings = True
run_after_build        = True
proj_name              = "Better VLC"
proj_version           = "0.1.0.0"
file_name              = "bvlc"
compiler               = "g++"
linker                 = "g++"
flags                  = ['-Wall','-Wextra','-O3','-static']
compiler_flags         = []
linker_flags           = []
output_path            = "bin"
source_path            = "src"
libs                   = []
pkgconf_libs           = []
lib_paths              = []
include_paths          = []
run_args               = []

exec_postbuild         = []
exec_prebuild          = []